<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DevicesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $devices = [
            [
                'brand' => 'Dell',
                'model' => 'Latitude 5320 2in1 Touchscreen',
                'processor_type' => 'i5-11',
                'ram' => '16GB',
                'storage' => '256GB',
                'daily_rate' => 160000,
                'monthly_rate' => 3000000,
                'yearly_rate' => 6000000,
                'units_available' => 100,
            ],
            [
                'brand' => 'Dell',
                'model' => 'Latitude 5320 Touchscreen',
                'processor_type' => 'i7-11',
                'ram' => '16GB',
                'storage' => '256GB',
                'daily_rate' => 175000,
                'monthly_rate' => 3300000,
                'yearly_rate' => 6300000,
                'units_available' => 500,
            ],
            [
                'brand' => 'Dell',
                'model' => 'Latitude 5400 Touchscreen',
                'processor_type' => 'i5-8',
                'ram' => '16GB',
                'storage' => '256GB',
                'daily_rate' => 110000,
                'monthly_rate' => 2400000,
                'yearly_rate' => 4600000,
                'units_available' => 50,
            ],
            [
                'brand' => 'Lenovo',
                'model' => 'Thinkpad T490 Touchscreen',
                'processor_type' => 'i5-8',
                'ram' => '8GB',
                'storage' => '256GB',
                'daily_rate' => 110000,
                'monthly_rate' => 2400000,
                'yearly_rate' => 4600000,
                'units_available' => 20,
            ],
            [
                'brand' => 'Lenovo',
                'model' => 'Thinkpad T480 Double VGA',
                'processor_type' => 'i7-8',
                'ram' => '8GB',
                'storage' => '256GB',
                'daily_rate' => 125000,
                'monthly_rate' => 2600000,
                'yearly_rate' => 5000000,
                'units_available' => 50,
            ],
            [
                'brand' => 'Lenovo',
                'model' => 'Thinkpad T470s Keyboard Backlight',
                'processor_type' => 'i5-6 8/256',
                'ram' => '8GB',
                'storage' => '256GB',
                'daily_rate' => 90000,
                'monthly_rate' => 1800000,
                'yearly_rate' => 3500000,
                'units_available' => 300,
            ],
            [
                'brand' => 'Lenovo',
                'model' => 'Thinkpad T460s Keyboard Backlight',
                'processor_type' => 'i5-6',
                'ram' => '8GB',
                'storage' => '256GB',
                'daily_rate' => 90000,
                'monthly_rate' => 1800000,
                'yearly_rate' => 3500000,
                'units_available' => 300,
            ],
            [
                'brand' => 'Lenovo',
                'model' => 'Thinkpad L470',
                'processor_type' => 'i5-7',
                'ram' => '8GB',
                'storage' => '256GB',
                'daily_rate' => 100000,
                'monthly_rate' => 2000000,
                'yearly_rate' => 3800000,
                'units_available' => 150,
            ],
            [
                'brand' => 'Lenovo',
                'model' => 'Thinkpad L460',
                'processor_type' => 'i5-6',
                'ram' => '8GB',
                'storage' => '256GB',
                'daily_rate' => 90000,
                'monthly_rate' => 1800000,
                'yearly_rate' => 3500000,
                'units_available' => 50,
            ],
            [
                'brand' => 'Lenovo',
                'model' => 'Thinkpad X270',
                'processor_type' => 'i5-6',
                'ram' => '8GB',
                'storage' => '256GB',
                'daily_rate' => 90000,
                'monthly_rate' => 1800000,
                'yearly_rate' => 3500000,
                'units_available' => 100,
            ],
            [
                'brand' => 'Lenovo',
                'model' => 'Thinkpad T470',
                'processor_type' => 'i5-6',
                'ram' => '8GB',
                'storage' => '256GB',
                'daily_rate' => 90000,
                'monthly_rate' => 1800000,
                'yearly_rate' => 3500000,
                'units_available' => 50,
            ],
            [
                'brand' => 'Lenovo',
                'model' => 'Thinkpad X280',
                'processor_type' => 'i5-8',
                'ram' => '8GB',
                'storage' => '256GB',
                'daily_rate' => 110000,
                'monthly_rate' => 2400000,
                'yearly_rate' => 4600000,
                'units_available' => 30,
            ],
            [
                'brand' => 'Lenovo',
                'model' => 'Thinkpad T480s',
                'processor_type' => 'i7-8',
                'ram' => '8GB',
                'storage' => '256GB',
                'daily_rate' => 125000,
                'monthly_rate' => 2600000,
                'yearly_rate' => 5000000,
                'units_available' => 50,
            ],
            [
                'brand' => 'Lenovo',
                'model' => 'Thinkpad L380 Yoga + Pen Stylus',
                'processor_type' => 'i5-8',
                'ram' => '8GB',
                'storage' => '256GB',
                'daily_rate' => 110000,
                'monthly_rate' => 2400000,
                'yearly_rate' => 4600000,
                'units_available' => 20,
            ],
            [
                'brand' => 'Lenovo',
                'model' => 'Thinkpad L480 Tc & Non Tc',
                'processor_type' => 'i5-8',
                'ram' => '8GB',
                'storage' => '256GB',
                'daily_rate' => 110000,
                'monthly_rate' => 2400000,
                'yearly_rate' => 4600000,
                'units_available' => 95,
            ],
            [
                'brand' => 'Lenovo',
                'model' => 'Thinkpad L490 Touchscreen',
                'processor_type' => 'i5-8',
                'ram' => '8GB',
                'storage' => '256GB',
                'daily_rate' => 110000,
                'monthly_rate' => 2400000,
                'yearly_rate' => 4600000,
                'units_available' => 60,
            ],
            [
                'brand' => 'Lenovo',
                'model' => 'Thinkpad L13',
                'processor_type' => 'i3-11',
                'ram' => '8GB',
                'storage' => '256GB',
                'daily_rate' => 120000,
                'monthly_rate' => 3300000,
                'yearly_rate' => 5900000,
                'units_available' => 10,
            ],
            [
                'brand' => 'Lenovo',
                'model' => 'Thinkpad L13',
                'processor_type' => 'i5-10',
                'ram' => '8GB',
                'storage' => '256GB',
                'daily_rate' => 140000,
                'monthly_rate' => 3900000,
                'yearly_rate' => 7500000,
                'units_available' => 10,
            ],
            [
                'brand' => 'HP',
                'model' => 'Elitebook 840 G4',
                'processor_type' => 'i5-7',
                'ram' => '8GB',
                'storage' => '256GB',
                'daily_rate' => 100000,
                'monthly_rate' => 2000000,
                'yearly_rate' => 3800000,
                'units_available' => 50,
            ]
        ];

        // Insert devices into the database
        DB::table('devices')->insert($devices);
    }
}
